erDiagram
    Category ||--o{ BlogPost : contains
    User ||--o{ BlogPost : writes
    
    Category {
        int id PK
        string name
        string slug
    }

    BlogPost {
        int id PK
        string title
        string slug
        boolean published
        date date
        text content
        text description
        int author FK
    }

    User {
        int id PK
        string username
        string email
        string password
    }
